# Cấu hình cho Baseline: ResNet50 + LSTM
experiment_name: "baseline_lstm_run1"

model:
  type: "lstm"
  embed_size: 256
  hidden_size: 512
  num_layers: 2

training:
  batch_size: 64
  learning_rate: 0.0003
  num_epochs: 15
  patience: 3            # Cho Early Stopping

data:
  root_dir: "data/ms_coco/train2014" #"demo_dataset" 
  train_ann_file: "data/ms_coco/annotations/subset_train.json" # "demo_dataset/demo_captions.json" 
  val_ann_file: "data/ms_coco/annotations/subset_val.json" # "demo_dataset/demo_captions.json" 
